/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

import Presentacio.ControladorPresentacio;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlosaires
 */
public class vistaDefinirHidato extends javax.swing.JFrame {

    /**
     * Creates new form vistaDefinirHidato
     */
    private ControladorPresentacio cp;
    
    public vistaDefinirHidato() {
        initComponents();
        this.setTitle("Hidato Game");
    }

    public vistaDefinirHidato(ControladorPresentacio cp) {
        initComponents();
        this.setTitle("Hidato Game");
        this.cp = cp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quadrat", "Triangle", "Hexagon" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "CA" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Mitja", "Dificil" }));

        jButton1.setText("Definir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dificultat;
        int dif;
        dificultat = jComboBox3.getSelectedItem().toString(); //Em passa la dificultat triada al combobox a string
        if (dificultat.equals("Facil")) dif = 1;
        else if (dificultat.equals("Mitja")) dif = 2;
        else if (dificultat.equals("Dificil")) dif = 3;
        else dif = -1;
        String tC = "Q";
        String tA = jComboBox2.getSelectedItem().toString();
        String mathead = new String("");
        try {
            mathead = cp.definirHidato(dif,tC,tA);
        } catch (IOException ex) {
            Logger.getLogger(vistaDefinirHidato.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(vistaDefinirHidato.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] parsed = mathead.split("\n");
        //System.out.println(parsed);
        String[] head = parsed[0].split(",");
        int files= Integer.parseInt(head[2]);
        int columnes = Integer.parseInt(head[3]);
        String matbona = new String();
        for (int i= 1; i <= files; ++i) {
             matbona += (parsed[i] +"\n");         
        }
        //System.out.println(matbona);
        String[] arreglaMat = matbona.split("\n");
        //for(int y=0; y<files;++y){
        //    System.out.println(arreglaMat[y] + " ");
        //}
        ArrayList<String> totSeparat = new ArrayList<String> (0);
        for(int i = 0; i < files; ++i){
            String[] aux = arreglaMat[i].split(",");
            for(int j = 0; j < columnes; ++j){
                totSeparat.add(aux[j]);
            }
        }
        
        String resultatMatriu = new String("");
        for(int i = 0; i < 14; ++i){
            for(int j = 0; j < 17; ++j){
                if(i < files && j < columnes){
                    if(j == 0) resultatMatriu += totSeparat.get(i*columnes+j);
                    else {
                        resultatMatriu += ",";
                        resultatMatriu += totSeparat.get(i*columnes+j);
                    }
                }
                else {
                    if(j == 0) resultatMatriu += "#";
                    else {
                        resultatMatriu += ",";
                        resultatMatriu += "#";
                    }
                }
            }
            resultatMatriu += "\n";
        }
        System.out.println(resultatMatriu);
        
        cp.resultatDefinirHidato(parsed[0],resultatMatriu);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cp.canviEscena("menutypeplay");
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaDefinirHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaDefinirHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaDefinirHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaDefinirHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaDefinirHidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    // End of variables declaration//GEN-END:variables
}
