/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

import Presentacio.ControladorPresentacio;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;

/**
 *
 * @author carlosaires
 */
public class vistaGenerarHidato extends javax.swing.JFrame {

    /**
     * Creates new form vistaGenerarHidato
     */
    
    private ControladorPresentacio cp;
    
    public vistaGenerarHidato() {
        initComponents();
        this.setTitle("Hidato Game");
    }

    public vistaGenerarHidato(ControladorPresentacio cp) {
        initComponents();
        this.setTitle("Hidato Game");
        this.cp = cp;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SeleccionaDificultat = new javax.swing.JComboBox<>();
        generaButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecciona la dificultat");

        SeleccionaDificultat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fàcil", "Mitjà", "Difícil" }));
        SeleccionaDificultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionaDificultatActionPerformed(evt);
            }
        });

        generaButton.setText("Genera");
        generaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SeleccionaDificultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(generaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SeleccionaDificultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(generaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionaDificultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionaDificultatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SeleccionaDificultatActionPerformed

    private void generaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaButtonActionPerformed
        // TODO add your handling code here:
        String dificultat;
        int dif;
        dificultat = SeleccionaDificultat.getSelectedItem().toString(); //Em passa la dificultat triada al combobox a string
        if (dificultat.equals("Fàcil")) dif = 1;
        else if (dificultat.equals("Mitjà")) dif = 2;
        else if (dificultat.equals("Difícil")) dif = 3;
        else dif = -1;
        String mathead = new String("");
        try {
            mathead = cp.generaHidato(dif);
        } catch (IOException ex) {
            Logger.getLogger(vistaGenerarHidato.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(vistaGenerarHidato.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] parsed = mathead.split("\n");
        //System.out.println(parsed);
        String[] head = parsed[0].split(",");
        int files= Integer.parseInt(head[2]);
        int columnes = Integer.parseInt(head[3]);
        String matbona = new String();
        for (int i= 1; i <= files; ++i) {
             matbona += (parsed[i] +"\n");         
        }
        //System.out.println(matbona);
        String[] arreglaMat = matbona.split("\n");
        //for(int y=0; y<files;++y){
        //    System.out.println(arreglaMat[y] + " ");
        //}
        ArrayList<String> totSeparat = new ArrayList<String> (0);
        for(int i = 0; i < files; ++i){
            String[] aux = arreglaMat[i].split(",");
            for(int j = 0; j < columnes; ++j){
                totSeparat.add(aux[j]);
            }
        }
        
        String resultatMatriu = new String("");
        for(int i = 0; i < 14; ++i){
            for(int j = 0; j < 17; ++j){
                if(i < files && j < columnes){
                    if(j == 0) resultatMatriu += totSeparat.get(i*columnes+j);
                    else {
                        resultatMatriu += ",";
                        resultatMatriu += totSeparat.get(i*columnes+j);
                    }
                }
                else {
                    if(j == 0) resultatMatriu += "#";
                    else {
                        resultatMatriu += ",";
                        resultatMatriu += "#";
                    }
                }
            }
            resultatMatriu += "\n";
        }
        System.out.println(resultatMatriu);
        
        cp.resultatGenerarHidato(parsed[0],resultatMatriu);
    }//GEN-LAST:event_generaButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        cp.canviEscena("menutypeplay");
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaGenerarHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaGenerarHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaGenerarHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaGenerarHidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaGenerarHidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JComboBox<String> SeleccionaDificultat;
    private javax.swing.JButton generaButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
